### ISSUE TITLE
使用cpu训练需要改代码吗

### ISSUE THREAD

**Issue by LakersUpAma** [cc2017111/NLP_engine_for_classification#1]
您的代码中分布式有三块显卡，我的机器只有cpu，这个要如何修改呢

**Comment by cc2017111** [comment]
如果你不是那么注重效率，那么其实tensorflow的MirroredStrategy可以向下兼容CPU，你只需要修改train.py line20
strategy = tf.distribute.MirroredStrategy(device="/cpu:0")并且在执行代码时添加环境变量CUDA_VISIBLE_DEVICES=-1应该就可以直接运行。
若你对细节十分考究，建议使用CentralStorageStrategy或OneDeviceStrategy修改代码，具体实现细节可以参考tensorflow官方文档。

**Comment by LakersUpAma** [comment]
好的，谢谢您，我试一下
